services:

  web:
    image: nginx:alpine
    ports:
      - 127.0.0.1:${HTTP_PORT:-80}:80
    volumes:
      - .docker/nginx/:/etc/nginx/conf.d/
      - ./build_local:/var/www/html

  php:
    build:
      context: .docker/php
    ports:
      - "127.0.0.1:${HTTP_PORT:-3000}:3000"
      - "127.0.0.1:${HTTP_PORT_BROWSERSYNC:-3001}:3001"
    volumes:
      - .:/var/www/html
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - SERVER_MODE=${SERVER_MODE:-watch}
      - TZ=${TZ:-America/Sao_Paulo}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-client_host=172.17.0.1 start_with_request=yes}
      - XDEBUG_MODE=${XDEBUG_MODE:-debug}
      - APP_ENV=${APP_ENV:-develop}
