language: php
php:
  - 7.4

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build_production
  repo: LibreCodeCoop/static
  target_branch: master
  keep-history: true
  email: travis-ci@librecode.coop
  name: Travis-CI
  fqdn: librecode.coop
  on:
    branch: master

before_script:
  - npm install -g gulp

before_deploy:
  - composer install
  - composer prod

script: /bin/true
